version: '3.8'
services:
  db:
    image: mysql:8.0
    container_name: article-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: article_db
      MYSQL_USER: article_user
      MYSQL_PASSWORD: article_pass
    ports:
      - '3306:3306'
    volumes:
      - ./db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - article-net

  backend:
    build: ./backend
    container_name: article-backend
    restart: always
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_USER: article_user
      DB_PASSWORD: article_pass
      DB_NAME: article_db
    ports:
      - '8080:8080'
    depends_on:
      db:
        condition: service_healthy
    networks:
      - article-net

  frontend:
    build: ./frontend
    container_name: article-frontend
    restart: always
    ports:
      - '3000:3000'
    depends_on:
      - backend
    networks:
      - article-net

networks:
  article-net:
    driver: bridge 